import { writeFileSync } from 'node:fs'
import { loadContent } from '../src/cli/store'

// Assemble content/*.yaml into a single JSON the browser imports directly — the web
// app never parses YAML or touches the filesystem. Regenerated by predev/prebuild.
const content = loadContent(new URL('../content', import.meta.url).pathname)
const out = new URL('../src/web/content.generated.json', import.meta.url)
writeFileSync(out, JSON.stringify(content))
console.log(`content.generated.json — ${content.lexicon.length} lexicon · ${content.templates.length} templates · ${content.modules.length} modules`)
